// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchMembers():Promise<Record<string, string>>;

export function StartBot(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;
