// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchMembers() {
  return window['go']['main']['App']['FetchMembers']();
}

export function StartBot(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartBot'](arg1, arg2, arg3, arg4);
}
